services:
  - type: web
    name: secureauth
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: touchless_auth
          property: connectionString
